### ISSUE TITLE
add Spyder

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#55]
https://pythonhosted.org/spyder/

Per user request (footprints 35316).

**Comment by alaniwi** [comment]
Tried in a virtual env prior to attempting RPM build. Fails with 

```
(venv)[builderdev@builder spyder-2.3.8]$ spyder
Traceback (most recent call last):
  File "/home/builderdev/test/venv/lib/python2.7/site-packages/spyder-2.3.8-py2.7.egg/spyderlib/spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/builderdev/test/venv/lib/python2.7/site-packages/spyder-2.3.8-py2.7.egg/spyderlib/spyder.py", line 2215, in run_spyder
    main.setup()
  File "/home/builderdev/test/venv/lib/python2.7/site-packages/spyder-2.3.8-py2.7.egg/spyderlib/spyder.py", line 734, in setup
    message=_("Spyder Internal Console\n\n"
  File "/home/builderdev/test/venv/lib/python2.7/site-packages/spyder-2.3.8-py2.7.egg/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/home/builderdev/test/venv/lib/python2.7/site-packages/spyder-2.3.8-py2.7.egg/spyderlib/widgets/findreplace.py", line 260, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/home/builderdev/test/venv/lib/python2.7/site-packages/spyder-2.3.8-py2.7.egg/spyderlib/qt/QtWebKit.py", line 12, in <module>
    from PySide.QtWebKit import *  # analysis:ignore
ImportError: No module named QtWebKit
```

**Comment by alaniwi** [comment]
Also depends on PyQt4 4.6+ or PySide 1.2.0+.  PySide 1.2.1 is provided in JAP, so okay (if QtWebKit dealt with), but need to record the dependency.

**Comment by alaniwi** [comment]
For system Python, there is `PyQt4-webkit-4.6.2-8.el6.x86_64.rpm` available, depending on `PyQt4` and `qt4`, and `qt4` is not currently installed on the builder. For python2.7, PySide is in the JAP, but not PyQt4.  `PySide.QtWebKit` exists and is documented at https://deptinfo-ensip.univ-poitiers.fr/ENS/pyside-docs/PySide/QtWebKit/index.html, but is not in PySide as currently built. Need to investigate how to get `PySide.QtWebKit`.
