### ISSUE TITLE
Install iris-sample-data package

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jasmin_scivm#95]
On user request (help scout ticket 9945)

Available from https://github.com/SciTools/iris-sample-data

Following one of the existing examples in the docstrings (see https://github.com/SciTools/iris/search?utf8=%E2%9C%93&q=ensemble_010.pp) currently gives:

```
>>> import iris
>>> iris.sample_data_path('GloSea4', 'ensemble_010.pp')
/usr/lib/python2.7/site-packages/iris/__init__.py:478: IrisDeprecation: iris.config.SAMPLE_DATA_DIR was deprecated in v1.10.0 and will be removed in a future Iris release. Install the 'iris_sample_data' package.
  warn_deprecated(wmsg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/iris/__init__.py", line 484, in sample_data_path
    'appropriate for general file access.'.format(target))
ValueError: Sample data file(s) at '/usr/lib/python2.7/site-packages/iris/sample_data/GloSea4/ensemble_010.pp' not found.
NB. This function is only for locating files in the iris sample data collection. It is not needed or appropriate for general file access.
```

**Comment by alaniwi** [comment]
Clean build and import. The `iris.sample_data_path('GloSea4', 'ensemble_010.pp')` returns a valid path.

**Comment by alaniwi** [comment]
Provided in 1.1-31. Long overdue close.
